//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCSC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCSC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        internal static string amountDownloadedText {
            get {
                return ResourceManager.GetString("amountDownloadedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string errName {
            get {
                return ResourceManager.GetString("errName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occured: .
        /// </summary>
        internal static string errorOccuredTitle {
            get {
                return ResourceManager.GetString("errorOccuredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minecraft Server Controller.
        /// </summary>
        internal static string longName {
            get {
                return ResourceManager.GetString("longName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string percentSymbol {
            get {
                return ResourceManager.GetString("percentSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string scWord_download {
            get {
                return ResourceManager.GetString("scWord_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill.
        /// </summary>
        internal static string scWord_kill {
            get {
                return ResourceManager.GetString("scWord_kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string scWord_start {
            get {
                return ResourceManager.GetString("scWord_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string scWord_stop {
            get {
                return ResourceManager.GetString("scWord_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string scWord_update {
            get {
                return ResourceManager.GetString("scWord_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server folder &apos;.
        /// </summary>
        internal static string serverFolderDeleted1 {
            get {
                return ResourceManager.GetString("serverFolderDeleted1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; was unexpectedly deleted. The program will now kill all running servers and restart..
        /// </summary>
        internal static string serverFolderDeleted2 {
            get {
                return ResourceManager.GetString("serverFolderDeleted2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCSC.
        /// </summary>
        internal static string shortName {
            get {
                return ResourceManager.GetString("shortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s left.
        /// </summary>
        internal static string timeLeftText {
            get {
                return ResourceManager.GetString("timeLeftText", resourceCulture);
            }
        }
    }
}
